### ISSUE TITLE
Roadmap of the Orleans.Saga to .netcore 2.1?

### ISSUE THREAD

**Issue by Shawn-Fan** [OrleansContrib/Orleans.Sagas#17]
Thanks for the excellent library. Do you have any plan to upgrade it to dotnet core 2.1 or above?

**Comment by creyke** [comment]
Glad to hear you are finding it useful. Sagas sits on the Orleans API so an upgrade to Net Core 2.1 should be trivial. As I'm not using it in production at the moment I haven't priotised this. I'm happy to take a PR - alternatively I could look at upgrading it over the Christmas period if there's interest / value?

**Comment by Shawn-Fan** [comment]
Thanks for your quick response and upgrade in advance. I am very interested in it for it is the kernel of the Micro-Servcies.

**Comment by creyke** [comment]
This is now complete.
