### ISSUE TITLE
Infinite growth of state after saga completions

### ISSUE THREAD

**Issue by highlyunavailable** [OrleansContrib/Orleans.Sagas#37]
The saga and completion grains never clean up their state. While history _may_ be valuable for the saga grain itself (though I would argue that the saga should at least have an option to clean itself up), the random bool and associated metadata of the cancellation grain should be cleaned up after the saga has completed for any reason.

**Comment by creyke** [comment]
To ensure idempotent requests to restart an already aborted saga, the `SagaCompletitionGrain` retains state after the saga has completed.

A sweeper service could be used to clean up saga state after a period of inactivity, although making this storage agnostic may be challenging.

Currently this has to be implemented manually, and is dependent on an individual storage provider.

Open to proposals on alternatives.

**Comment by highlyunavailable** [comment]
Makes sense, but I was wondering why the `SagaCompletitionGrain` isn't purged after the saga has completed.  In fact, I'm curious as to why the `SagaCompletitionGrain` exists at all, since the `SagaGrain` should be able to take care of storage. I saw a comment about storage mutation, but that feels like there's a larger problem if the storage of the saga is being mutated by something other than the Saga grain while in-progress.

**Comment by creyke** [comment]
Sorry for the delay. The completion grain is separate so it can be "always available" for immediate cancellation request persistence, even when the saga grain is active. It's technically possible to do this with [reentrancy](https://dotnet.github.io/orleans/docs/grains/reentrancy.html), but this wasn't the design decision at the time.

I'm open to changing it, it's just a case of understanding how significant the issue with it is currently and finding time to do it / someone PRing the changes.
