### ISSUE TITLE
Getting SagaProperties added to context from activities

### ISSUE THREAD

**Issue by ElanHasson** [OrleansContrib/Orleans.Sagas#51]
In my activities I'm emitting state information into SagaProperties.

How can I access them after/during the saga execution?

**Comment by creyke** [comment]
Saga properties are available for subsequent activities via the `IActivityContext` for example [like this](https://github.com/OrleansContrib/Orleans.Sagas/blob/5d9f58d831456f1d6cdbe7e3d67e97adf961a7e8/Orleans.Sagas.Samples.Activities/RequestActivity.cs#L20).

**Comment by ElanHasson** [comment]
Right-- That's what I did.

`context.SagaProperties` doesn't seem to carry through.

I did a `context.SagaProperties.Add()` in Activity A and the `context.SagaProperties` is an empty set in activity B.

**Comment by creyke** [comment]
I just tested this on the .NET 5 samples (dependency injection sample) and it appears to be working.

It's worth noting that the internal `existingProperties` collection is the one you want to be checking...

![image](https://user-images.githubusercontent.com/1805709/135055478-1c682b54-2757-43e1-af26-123f2ac4ea41.png)

**Comment by ElanHasson** [comment]
Let me dig deeper and see, will get back to you.

**Comment by ElanHasson** [comment]
I see them in the list-- My problem was the type was abstract.
